// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CCRM2.Shared.Models
{
    [Table("DataTable", Schema = "crm")]
    public partial class DataTable
    {
        [Key]
        public int Id { get; set; }
        [Column("Title")]
        public string Title { get; set; }
        [Column("Selected")]
        public bool Selected { get; set; }
    }
}